---
- name: Create resourcegroup
  hosts: localhost
  tasks:
   - name: Create a Resource Group
     azure_rm_resourcegroup:
        name: {{rg_name}}
        location: {{rg_location}}
     register: rg
   - name: Display
     debug:
       var: rg
...
