- name: Get VM Info
  hosts: localhost
  tasks:
    - name: Get facts for all virtual machines of a resource group
      azure_rm_virtualmachine_info:
        resource_group: myResourceGroup
      register: vm_info
