---
- hosts: localhost
  tasks:
    - name: Get resource groups facts
      azure_rm_resourcegroup_info:
        name: {{ rg_name }}
      register: rg
    - name: Print
      debug:
       var: rg
      
